language: ruby

rvm:
  - 2.0.0
  - 2.1
  - ruby-head

services:
  - redis-server

git:
  strategy: tarball

sudo: false

bundler_args: --jobs=3 --retry=3 --deployment --local --without development

before_install:
  - gem update --system 2.2.2
  - gem --version

before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare

matrix:
  allow_failures:
    - rvm: 2.1
    - rvm: ruby-head
